### ISSUE TITLE
Security Lab

### ISSUE THREAD

**Issue by ronniet7626** [ronniet7626/SEBC#5]

**Comment by ronniet7626** [comment]
Unable to get TLS working correctly, followed detailed instructions here:

https://www.cloudera.com/documentation/enterprise/5-14-x/topics/sg_self_signed_tls.html

Set configuration in Cloudera Manager Services, unable to achieve secure connection.

**Comment by rafaelarana** [comment]
Well done on kerberos & Sentry.
